### ISSUE TITLE
Norton 360 marks SSIMS-FLOW.exe as a virus

### ISSUE THREAD

**Issue by bzindovic** [ljubicicrobert/SSIMS-Flow#7]
Norton 360 marked SSIMS-FLOW.exe. As this is a false positive, it should be noted in the documentation.

**Comment by bzindovic** [comment]
This is the Norton 360 Info regarding the removal:
![SSIMS_Flow exe_removal](https://user-images.githubusercontent.com/1198004/170255938-11638c00-d1a3-426c-8056-19df0907073b.png)

**Comment by ljubicicrobert** [comment]
This is now noted in the README, but is a false positive. Scanned with Windows Defender and found clean. However, source code for DLLs will soon be released for transparency.

**Comment by bzindovic** [comment]
As this is a false positive, I'll close this issue.
