### ISSUE TITLE
Norton 360 marks filtering.dll as a virus

### ISSUE THREAD

**Issue by bzindovic** [ljubicicrobert/SSIMS-Flow#8]
Norton 360 marked filtering.dll. As this is a false positive, it should be noted in the documentation.

**Comment by bzindovic** [comment]
This is the Norton 360 Info regarding the removal:
![filtering dll_removal](https://user-images.githubusercontent.com/1198004/170255616-05cbc76f-e177-4c73-828d-2ff63c5b1810.png)

**Comment by ljubicicrobert** [comment]
See #7.

**Comment by ljubicicrobert** [comment]
Added a note in the README.md with the explanation.
