### ISSUE TITLE
Norton 360 marks pooling.dll as a virus

### ISSUE THREAD

**Issue by bzindovic** [ljubicicrobert/SSIMS-Flow#9]
Norton 360 marked pooling.dll. As this is a false positive, it should be noted in the documentation.

**Comment by bzindovic** [comment]
This is the Norton 360 Info regarding the removal:
![pooling dll_removal](https://user-images.githubusercontent.com/1198004/170255351-52295eb6-827d-42d6-a1bb-6bc47b045cbd.png)

**Comment by ljubicicrobert** [comment]
See #7.

**Comment by bzindovic** [comment]
As this is a false positive, I'll close this issue.
